#!/bin/bash

java -jar target/discover-cli-0.0.15-SNAPSHOT-shaded.jar -IVFilePath /etc/remote/iv -KeyFilePath /etc/remote/key -DiscoverUsername $(decrypt-password DiscoverUsername) -DiscoverPassword $(decrypt-password DiscoverPassword) -Debug true
