#!/bin/bash

java -jar target/prudential-cli-0.0.15-SNAPSHOT-shaded.jar -IVFilePath /etc/remote/iv -KeyFilePath /etc/remote/key -PrudentialUsername $(decrypt-password PrudentialUsername) -PrudentialPassword $(decrypt-password PrudentialPassword) -Debug true
