#!/bin/bash

java -jar target/pnc-cli-0.0.15-SNAPSHOT-shaded.jar -IVFilePath /etc/remote/iv -KeyFilePath /etc/remote/key -PNCUsername $(decrypt-password PNCUsername) -PNCPassword $(decrypt-password PNCPassword) -Debug true
