#!/bin/bash

java -jar target/voya-cli-0.0.15-SNAPSHOT-shaded.jar -IVFilePath /etc/remote/iv -KeyFilePath /etc/remote/key -VoyaUsername $(decrypt-password VoyaUsername) -VoyaPassword $(decrypt-password VoyaUsername) -Debug true
